// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ForceStopGame():Promise<string>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function LaunchGame(arg1:string,arg2:number,arg3:boolean,arg4:string):Promise<string>;
